spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:35432/postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true

hashSecret: SECRET
complexity: 12
jwtSecret: "SECRET"


management:
  endpoints:
    web:
      exposure:
        include: '*'